#include "ProjectInfo.h"

#include "Runtime/Core/Base/Macro.h"
#include "Runtime/Core/Serialize/SerializeUtility.h"
#include "Runtime/File/FileSystem.h"
#include "Runtime/Function/Command/CommandSystem.h"
#include "core/Log/LogSystem.h"

#include <ctime>
#include <fstream>
#include <iomanip>
#include <memory>
#include <sstream>
#include <system_error>

IMPLEMENT_REGISTER_CLASS(ProjectInfo)
IMPLEMENT_OBJECT_SERAILIZE(ProjectInfo)

namespace
{
    // -----------------------------------------------------------------------------
    // Scaffolding templates for first-time project open.
    //
    // Kept as raw string literals next to the only function that uses them so the
    // scripting subsystem stays self-contained - no extra header, no extra TU.
    // Rationale per template documented inline so future maintainers can tweak
    // versions/options without re-deriving the design intent.
    // -----------------------------------------------------------------------------

    // tsconfig.json:
    //   * `outDir` matches GetIntermediateScriptsRoot()'s relative form ("Intermediate/Scripts").
    //   * `rootDir` matches GetScriptsRoot()'s relative form ("Scripts") - kept at the
    //     project root (peer of Assets/) per the layout decision in ProjectInfo.h.
    //   * `module: commonjs` is mandated by puerts/QuickJS - its loader expects
    //     `module.exports = ...` shape, ESM is not wired in yet.
    //   * `experimentalDecorators` reserved for the future @SerializedField decorator
    //     used by Phase 5 inspector binding.
    //   * `strict: false` chosen as default to lower the entry barrier; users can
    //     flip it to true once their scripts stabilise.
    constexpr const char* kTsConfigTemplate = R"({
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "outDir": "./Intermediate/Scripts",
    "rootDir": "./Scripts",
    "sourceMap": true,
    "experimentalDecorators": true,
    "strict": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": [
    "Scripts/**/*.ts",
    "Intermediate/Typings/**/*.d.ts"
  ]
}
)";

    // package.json:
    //   * Pinned typescript major version (5.x) - we don't track every TS release;
    //     the engine only relies on commonjs emit which has been stable since 1.x.
    //   * `private: true` so `npm publish` accidents don't leak user projects.
    //   * No `scripts.build` entry on purpose: the engine drives `tsc --watch`
    //     itself in Phase 3; users are free to add their own commands here.
    constexpr const char* kPackageJsonTemplate = R"({
  "name": "zengine-project-scripts",
  "version": "0.1.0",
  "private": true,
  "description": "TypeScript sources for a ZEngine project. Compiled by the engine via tsc --watch.",
  "devDependencies": {
    "typescript": "^5.4.0"
  }
}
)";

    // Packages/manifest.json (ZPM, Unity UPM-style; NOT the npm package.json above).
    constexpr const char* kProjectPackagesManifestTemplate = R"({
  "dependencies": {
    "com.zengine.ugui": "1.0.0"
  }
}
)";

    // .gitignore additions. We only *append* (and only if our marker isn't already
    // in the file) so we never clobber the user's hand-crafted ignore rules.
    //
    // /Assets/_Generated/ is the bake-output bucket for Data/ (CSV->.zasset) and
    // any future generated-asset pipeline. It deliberately lives UNDER Assets/
    // so AssetRegistry picks it up with zero extra code; the gitignore entry
    // keeps the build artifacts out of VCS.
    constexpr const char* kGitignoreMarker = "# >>> ZEngine scripting scaffold >>>";
    constexpr const char* kGitignoreSection =
        "\n# >>> ZEngine scripting scaffold >>>\n"
        "# Generated by ProjectInfo::EnsureScriptsScaffold() - do not edit between markers.\n"
        "/Intermediate/\n"
        "/node_modules/\n"
        "*.tsbuildinfo\n"
        "/Assets/_Generated/\n"
        "# <<< ZEngine scripting scaffold <<<\n";

    // zengine.d.ts:
    //   * Lives under <project>/Intermediate/Typings/ which is gitignored - the
    //     engine OWNS this file and overwrites it on every project open. Users
    //     should not hand-edit it; if they do, their changes will be wiped on
    //     the next launch (this is the same contract Unity uses for the
    //     auto-generated UnityEngine.dll typings).
    //   * Mirrors the runtime shim installed by ScriptEnv::InstallConsoleAndDebugGlobals
    //     (see Wrapper/ScriptEnv.cpp) plus the __zNewInstance helper used by
    //     ScriptEnv::CreateInstance. Phase 5 ships the minimum needed to compile
    //     a user `class X extends Behaviour { OnUpdate(dt: number) {} }`; phases 7+
    //     will extend it with engine binding types (GameObject, Vector3, etc).
    //   * `declare class Behaviour` (not `interface`) because user scripts use
    //     `extends Behaviour`, which requires a constructor in TS's eyes.
    constexpr const char* kZEngineDtsTemplate =
        "// =========================================================================\n"
        "// AUTO-GENERATED by ZEngine. Do NOT edit -- regenerated on every project open.\n"
        "// Source of truth: ProjectInfo::EnsureScriptsScaffold (kZEngineDtsTemplate).\n"
        "// =========================================================================\n"
        "\n"
        "/** Base class for any script that wants to be attached to a GameObject. */\n"
        "declare class Behaviour {\n"
        "    /** Called once when the component is first activated. */\n"
        "    OnAwake?(): void;\n"
        "    /** Called once after OnAwake, before the first OnUpdate. */\n"
        "    OnStart?(): void;\n"
        "    /** Per-frame update. `dt` is delta time in seconds. */\n"
        "    OnUpdate?(dt: number): void;\n"
        "    /** Called when the component is being torn down. Last chance to release resources. */\n"
        "    OnDestroy?(): void;\n"
        "}\n"
        "\n"
        "/** Engine-side logging facade. Routes to the [ZScripting] log category. */\n"
        "declare namespace Debug {\n"
        "    function Log(...args: any[]): void;\n"
        "    function LogWarning(...args: any[]): void;\n"
        "    function LogError(...args: any[]): void;\n"
        "}\n"
        "\n"
        "/** Standard browser-style console, also routed into [ZScripting]. */\n"
        "declare const console: {\n"
        "    log(...args: any[]): void;\n"
        "    info(...args: any[]): void;\n"
        "    debug(...args: any[]): void;\n"
        "    warn(...args: any[]): void;\n"
        "    error(...args: any[]): void;\n"
        "};\n"
        "\n"
        "// Internal helper - keep declared so user code that accidentally references\n"
        "// it doesn't get a fresh `any` (which would mask typos).\n"
        "declare function __zNewInstance<T>(ctor: { new(): T }): T;\n";

    /// Idempotent "create file if missing" helper. Returns true on success or
    /// when the file already exists; false only on actual I/O failure (which is
    /// logged at WARNING - scaffolding is non-fatal).
    bool writeFileIfMissing(const std::filesystem::path& path, const char* content)
    {
        std::error_code ec;
        if (std::filesystem::exists(path, ec))
        {
            return true;
        }
        std::ofstream ofs(path, std::ios::binary);
        if (!ofs.is_open())
        {
            LOG_WARNING(ZProjectInfo, "ensureScriptsScaffold: cannot create {}", path.generic_string());
            return false;
        }
        ofs << content;
        return ofs.good();
    }

    /// Append the scripting ignore-section to .gitignore if our marker isn't there
    /// yet. We never rewrite existing content; in the worst case the user gets a
    /// duplicate empty line which is harmless.
    bool ensureGitignoreSection(const std::filesystem::path& gitignore_path)
    {
        std::error_code ec;
        std::string existing;
        if (std::filesystem::exists(gitignore_path, ec))
        {
            std::ifstream ifs(gitignore_path, std::ios::binary);
            if (ifs.is_open())
            {
                std::ostringstream ss;
                ss << ifs.rdbuf();
                existing = ss.str();
            }
            if (existing.find(kGitignoreMarker) != std::string::npos)
            {
                return true;  // already set up
            }
        }

        std::ofstream ofs(gitignore_path, std::ios::binary | std::ios::app);
        if (!ofs.is_open())
        {
            LOG_WARNING(ZProjectInfo, "ensureScriptsScaffold: cannot append to {}", gitignore_path.generic_string());
            return false;
        }
        ofs << kGitignoreSection;
        return ofs.good();
    }
}  // namespace

bool ProjectInfo::Initialize()
{
    auto&& commandSystem = GET_SYSTEM(CommandSystem);
    m_WorkingDir = commandSystem->GetWorkingDir();
    const bool loaded = LoadFromFile(commandSystem->GetProjectPath());

    // Scaffolding is best-effort and only meaningful once we have a project root.
    // We run it AFTER load so user-overridden scripts_dir / intermediate_dir take
    // effect; we run it even if load failed but project_path got set (e.g. user
    // pointed at a brand-new directory) so the very first launch produces the
    // expected files.
    if (!project_path.empty())
    {
        EnsureScriptsScaffold();
    }
    return loaded;
}

bool ProjectInfo::LoadFromFile(const std::filesystem::path& project_file_path)
{
    if (!std::filesystem::exists(project_file_path))
    {
        return false;
    }

    project_file = project_file_path;
    project_path = project_file_path.parent_path();

    std::ifstream file(project_file_path);
    if (!file.is_open())
    {
        return false;
    }
    return GET_SYSTEM(FileSystem)->LoadAssetByJson(this, project_file_path);
}

bool ProjectInfo::SaveToFile() const
{
    if (project_file.empty())
    {
        return false;
    }

    return GET_SYSTEM(FileSystem)->saveAssetJson(*this, project_file);
}

bool ProjectInfo::IsValid() const
{
    return !name.empty() && !project_file.empty() && std::filesystem::exists(project_file) &&
           std::filesystem::exists(project_path);
}

std::filesystem::path ProjectInfo::GetProjectRoot() const
{
    return project_path;
}

std::filesystem::path ProjectInfo::GetProjectContent() const
{
    const std::string& asset_dir = content_dir.empty() ? std::string("Assets") : content_dir;
    return project_path / asset_dir;
}

std::filesystem::path ProjectInfo::GetScriptsRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    // Peer of <project>/Assets/. See ProjectInfo.h for why this isn't nested
    // under GetProjectContent().
    const char* sd = scripts_dir.empty() ? "Scripts" : scripts_dir.c_str();
    return project_path / sd;
}

std::filesystem::path ProjectInfo::GetIntermediateScriptsRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    const char* interm = intermediate_dir.empty() ? "Intermediate" : intermediate_dir.c_str();
    return project_path / interm / "Scripts";
}

std::filesystem::path ProjectInfo::GetAssetRegistryRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    // Peer of Assets/ and Scripts/. Intentionally NOT under Intermediate/:
    // the registry IS the GUID source of truth, losing it on a fresh clone
    // would silently break cross-scene script references. See AGENTS.md 2.2.
    return project_path / "AssetRegistry";
}

std::filesystem::path ProjectInfo::GetScriptRegistryPath() const
{
    const auto root = GetAssetRegistryRoot();
    if (root.empty())
    {
        return {};
    }
    return root / "script_registry.json";
}

std::filesystem::path ProjectInfo::GetShaderRegistryPath() const
{
    const auto root = GetAssetRegistryRoot();
    if (root.empty())
    {
        return {};
    }
    return root / "shader_registry.json";
}

std::filesystem::path ProjectInfo::GetTsConfigPath() const
{
    if (project_path.empty())
    {
        return {};
    }
    return project_path / "tsconfig.json";
}

std::filesystem::path ProjectInfo::GetPackageJsonPath() const
{
    if (project_path.empty())
    {
        return {};
    }
    return project_path / "package.json";
}

std::filesystem::path ProjectInfo::GetPackagesRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    return project_path / "Packages";
}

std::filesystem::path ProjectInfo::GetProjectPackagesManifestPath() const
{
    const auto root = GetPackagesRoot();
    if (root.empty())
    {
        return {};
    }
    return root / "manifest.json";
}

std::filesystem::path ProjectInfo::GetShadersRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    // Peer of <project>/Assets/ and <project>/Scripts/. See AGENTS.md 2.2 -
    // shader source files (.shader / .hlsl / .compute / .raytrace) live here
    // rather than under Assets/, mirroring the per-project Scripts layout.
    const char* sd = shaders_dir.empty() ? "Shaders" : shaders_dir.c_str();
    return project_path / sd;
}

std::filesystem::path ProjectInfo::GetIntermediateShadersRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    const char* interm = intermediate_dir.empty() ? "Intermediate" : intermediate_dir.c_str();
    return project_path / interm / "Shaders";
}

std::filesystem::path ProjectInfo::GetIntermediateDDCRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    const char* interm = intermediate_dir.empty() ? "Intermediate" : intermediate_dir.c_str();
    return project_path / interm / "DDC";
}

std::filesystem::path ProjectInfo::GetIntermediateCookedRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    const char* interm = intermediate_dir.empty() ? "Intermediate" : intermediate_dir.c_str();
    return project_path / interm / "Cooked";
}

std::filesystem::path ProjectInfo::GetDataRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    // Peer of <project>/Assets/, Scripts/, Shaders/. Holds CSV/XLSX source
    // tables; **checked into VCS**. The compiled .zasset products live under
    // GetGeneratedDataRoot() (which is inside Assets/ but gitignored).
    const char* dd = data_dir.empty() ? "Data" : data_dir.c_str();
    return project_path / dd;
}

std::filesystem::path ProjectInfo::GetGeneratedAssetsRoot() const
{
    if (project_path.empty())
    {
        return {};
    }
    // <project>/<content_dir>/_Generated/. Lives UNDER Assets/ so the
    // AssetRegistry scan picks up generated .zasset files with zero extra
    // wiring; gitignored via the scaffold marker block.
    const std::string& asset_dir = content_dir.empty() ? std::string("Assets") : content_dir;
    return project_path / asset_dir / "_Generated";
}

std::filesystem::path ProjectInfo::GetGeneratedDataRoot() const
{
    const auto root = GetGeneratedAssetsRoot();
    if (root.empty())
    {
        return {};
    }
    return root / "Data";
}

std::filesystem::path ProjectInfo::GetGeneratedShadersRoot() const
{
    const auto root = GetGeneratedAssetsRoot();
    if (root.empty())
    {
        return {};
    }
    return root / "Shaders";
}

bool ProjectInfo::EnsureScriptsScaffold()
{
    if (project_path.empty())
    {
        // No project loaded - nothing to scaffold. Caller is expected to gate
        // on this; we treat it as a soft no-op to keep Initialize() linear.
        return false;
    }

    bool all_ok = true;
    std::error_code ec;

    // 1) Create directories. create_directories is a no-op if they already exist.
    //    Failures here are logged but non-fatal: the user can still author scripts
    //    by hand, and Phase 2/3 will surface the actual error when they try to use
    //    a missing folder.
    const std::filesystem::path scripts_root = GetScriptsRoot();
    const std::filesystem::path interm_root = GetIntermediateScriptsRoot();
    if (!scripts_root.empty())
    {
        std::filesystem::create_directories(scripts_root, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create scripts dir {}: {}",
                        scripts_root.generic_string(),
                        ec.message());
            all_ok = false;
            ec.clear();
        }
    }
    if (!interm_root.empty())
    {
        std::filesystem::create_directories(interm_root, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create intermediate dir {}: {}",
                        interm_root.generic_string(),
                        ec.message());
            all_ok = false;
            ec.clear();
        }
    }

    // Cooked/ holds per-platform cooked .zasset variants (texture cook Phase 6).
    // Gitignored (it lives under Intermediate/). Created here so the cook step
    // never has to special-case a missing root; the per-platform subdir is made
    // on demand by the cook walk.
    const std::filesystem::path cooked_root = GetIntermediateCookedRoot();
    if (!cooked_root.empty())
    {
        std::filesystem::create_directories(cooked_root, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create cooked dir {}: {}",
                        cooked_root.generic_string(),
                        ec.message());
            ec.clear();
        }
    }

    // AssetRegistry/ holds the path<->GUID maps for text-source assets and
    // IS checked into VCS (see AGENTS.md 2.2). Creating it on first launch
    // means ScriptRegistry can write its JSON without an extra mkdir step.
    const std::filesystem::path registry_root = GetAssetRegistryRoot();
    if (!registry_root.empty())
    {
        std::filesystem::create_directories(registry_root, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create asset-registry dir {}: {}",
                        registry_root.generic_string(),
                        ec.message());
            all_ok = false;
            ec.clear();
        }
    }

    // 2) Write tsconfig.json / package.json only if missing - never overwrite a
    //    user-customised file. This is the same contract as Unity's Library/
    //    autogenerated files (regenerated only when absent).
    const std::filesystem::path packages_root = GetPackagesRoot();
    if (!packages_root.empty())
    {
        std::filesystem::create_directories(packages_root, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create Packages dir {}: {}",
                        packages_root.generic_string(),
                        ec.message());
            all_ok = false;
            ec.clear();
        }
    }
    all_ok &= writeFileIfMissing(GetTsConfigPath(), kTsConfigTemplate);
    all_ok &= writeFileIfMissing(GetPackageJsonPath(), kPackageJsonTemplate);
    all_ok &= writeFileIfMissing(GetProjectPackagesManifestPath(), kProjectPackagesManifestTemplate);

    // 2b) Write the engine-owned typings file. Unlike tsconfig/package.json
    //     this lives under Intermediate/ (gitignored) and is regenerated
    //     unconditionally so it stays in sync with whatever shim ScriptEnv
    //     installs at runtime. Users who want richer typings should add their
    //     own .d.ts under Intermediate/Typings/ -- tsconfig already globs the
    //     whole folder.
    if (!interm_root.empty())
    {
        const std::filesystem::path typings_dir = project_path / (intermediate_dir.empty() ? "Intermediate" : intermediate_dir.c_str()) / "Typings";
        std::filesystem::create_directories(typings_dir, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create typings dir {}: {}",
                        typings_dir.generic_string(),
                        ec.message());
            ec.clear();
        }
        else
        {
            const auto dts_path = typings_dir / "zengine.d.ts";
            std::ofstream ofs(dts_path, std::ios::binary | std::ios::trunc);
            if (!ofs.is_open() || !(ofs << kZEngineDtsTemplate).good())
            {
                LOG_WARNING(ZProjectInfo,
                            "ensureScriptsScaffold: failed to write {}",
                            dts_path.generic_string());
                all_ok = false;
            }
        }
    }

    // 3) Append (not overwrite) ignore rules so users who already have a
    //    .gitignore tracking other patterns keep their existing rules.
    all_ok &= ensureGitignoreSection(project_path / ".gitignore");

    // 4) Shader scaffold. Mirrors steps (1) for the Shaders subsystem:
    //    - <project>/<shaders_dir>/        : user-authored .shader sources
    //    - <project>/<intermediate>/Shaders/: compiled cache (gitignored
    //      automatically because the marker block in step (3) covers the
    //      whole /Intermediate/ tree).
    //    No registry / config files for shaders yet; ShaderRegistry is
    //    deferred until shaders need GUID-stable references (see AGENTS.md
    //    2.2 rationale for ScriptRegistry).
    const std::filesystem::path shaders_root = GetShadersRoot();
    if (!shaders_root.empty())
    {
        std::filesystem::create_directories(shaders_root, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create shaders dir {}: {}",
                        shaders_root.generic_string(),
                        ec.message());
            all_ok = false;
            ec.clear();
        }
    }
    const std::filesystem::path interm_shaders = GetIntermediateShadersRoot();
    if (!interm_shaders.empty())
    {
        std::filesystem::create_directories(interm_shaders, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create intermediate shaders dir {}: {}",
                        interm_shaders.generic_string(),
                        ec.message());
            all_ok = false;
            ec.clear();
        }
    }

    // 5) Data scaffold. Mirrors steps (1)/(4) for the data-table subsystem:
    //    - <project>/<data_dir>/             : user-authored .csv (V1) / .xlsx (V2) sources.
    //    - <content>/_Generated/Data/        : compile output, one .zasset per .csv,
    //      same relative path. Placed UNDER Assets/ so AssetRegistry's existing
    //      scan picks the products up with zero extra wiring; the whole
    //      _Generated/ subtree is gitignored via the marker block in step (3).
    //    No registry yet -- the .zasset header carries its own GUID via
    //    SerializedFile, identical to all other binary assets.
    const std::filesystem::path data_root = GetDataRoot();
    if (!data_root.empty())
    {
        std::filesystem::create_directories(data_root, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create data dir {}: {}",
                        data_root.generic_string(),
                        ec.message());
            all_ok = false;
            ec.clear();
        }
    }
    const std::filesystem::path generated_data = GetGeneratedDataRoot();
    if (!generated_data.empty())
    {
        std::filesystem::create_directories(generated_data, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create generated data dir {}: {}",
                        generated_data.generic_string(),
                        ec.message());
            all_ok = false;
            ec.clear();
        }
    }

    // 5b) Generated Shaders bucket: <content>/_Generated/Shaders/.
    //     Same pattern as _Generated/Data/: placed UNDER Assets/ so
    //     AssetRegistry picks up the .zasset files with zero extra wiring.
    const std::filesystem::path generated_shaders = GetGeneratedShadersRoot();
    if (!generated_shaders.empty())
    {
        std::filesystem::create_directories(generated_shaders, ec);
        if (ec)
        {
            LOG_WARNING(ZProjectInfo,
                        "ensureScriptsScaffold: failed to create generated shaders dir {}: {}",
                        generated_shaders.generic_string(),
                        ec.message());
            all_ok = false;
            ec.clear();
        }
    }

    LOG_INFO(ZProjectInfo,
             "Scripting scaffold ready at {} (scripts: {}, intermediate: {})",
             project_path.generic_string(),
             scripts_root.generic_string(),
             interm_root.generic_string());
    LOG_INFO(ZProjectInfo,
             "Shader scaffold ready (shaders: {}, intermediate: {})",
             shaders_root.generic_string(),
             interm_shaders.generic_string());
    LOG_INFO(ZProjectInfo,
             "Data scaffold ready (data: {}, generated: {})",
             data_root.generic_string(),
             generated_data.generic_string());
    return all_ok;
}

template<typename TransferFunction>
void ProjectInfo::Transfer(TransferFunction& transfer)
{
    transfer.Transfer(name, "name");
    // New scripting fields. Persisted so users can rename Scripts/ → Code/ etc.
    // and have it survive a reload. Defaulted in the header, so existing
    // .zproject files without these keys still load correctly.
    transfer.Transfer(scripts_dir, "scripts_dir");
    transfer.Transfer(intermediate_dir, "intermediate_dir");
    transfer.Transfer(shaders_dir, "shaders_dir");
    transfer.Transfer(data_dir, "data_dir");
}