#pragma once

#include "Runtime/Core/Base/EngineSystem.h"
#include "Runtime/Core/Base/Macro.h"
#include "Runtime/Core/Memory/MemoryManager.h"
#include "Runtime/Core/Serialize/Remapper.h"
#include "Runtime/Core/Serialize/SerializedFileLoadError.h"
#include "Runtime/Core/Serialize/WriteData.h"
#include "Runtime/File/FileSystem.h"
#include "Runtime/Platform/Encoding/EncodingUtils.h"
#include "Runtime/Resource/ResourceManager.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <functional>
#include <sstream>
#include <string>
#include <type_traits>
#include <unordered_set>
#include <utility>
#include <vector>

enum class AssetFormat
{
    JSON,
    Binary
};

class Object;
class Remapper;
class MaterialRes;
class ShaderRes;
struct StreamNameSpace

{
    SerializedFile* stream;
    SerializedFileLoadError loadError;
    StreamNameSpace()
        : stream(nullptr) {}
};

class AssetManager : public IEngineSystem
{
public:
    enum
    {
        kCacheSize = 1024 * 64,
        kCacheSizeForWriting = 1024 * 1024
    };
    enum LockFlags
    {
        kLockFlagNone = 0
    };
    std::string GetName() const override { return GET_CLASS_NAME(AssetManager); }
    bool Initialize() override { return true; }
    void Shutdown() override {}
    SystemInitPhase GetInitPhase() const override { return SystemInitPhase::Resource; }
    /**
     * @brief Load asset from file (auto-detect format by extension)
     * Supports .json (JSON) and .zasset (Binary) formats
     */
    template<typename AssetType>
    AssetType* loadAsset(const eastl::string& asset_url) const
    {
        std::filesystem::path asset_path = GetFullPath(asset_url);
        std::string extension = asset_path.extension().string();
        std::string asset_type_ext = asset_path.stem().extension().string();
        std::transform(extension.begin(), extension.end(), extension.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        std::transform(asset_type_ext.begin(), asset_type_ext.end(), asset_type_ext.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

        auto&& fileSystem = GET_SYSTEM(FileSystem);
        if (extension == ".json")
        {
            return fileSystem->loadAssetJson<AssetType>(asset_path);
        }

        if (extension == ".zasset")

        {
            return const_cast<AssetManager*>(this)->ReadObject<AssetType>(asset_path);
        }
        return fileSystem->loadAssetJson<AssetType>(asset_path);
    }

    // PR-SE3a-migrate -- Demand-load an Object given only its runtime
    // InstanceID. Walks the Remapper's reverse map to recover
    // (serializedFileIndex, localIdentifierInFile), pulls the path out
    // of the namespace table, and forwards to ReadObject(path, type).
    // The base implementation can do this generically because both
    // Remapper and the path-namespace table live on the base class.
    // Returns nullptr when the InstanceID isn't backed by any
    // SerializedFile (heap-only objects, dangling refs, runtime-only
    // graphs that haven't been persisted yet) -- the existing
    // ObjectManager fallthrough in PPtr<T>::operator T*() already
    // handles that case.
    //
    // Type discovery: the persistent type ID lives inside the on-disk
    // SerializedFile, so we open it once via GetSerializedFile() and
    // map persistentTypeID -> Type* via TypeManager. Subsequent reads
    // of the same instanceID short-circuit through ObjectManager's
    // IDToPointer cache (Produce registered the object on first load),
    // so the open-cost is paid once per unique target file.
    Object* ReadObject(int32_t instanceID);

    Object& ProduceSingletonAsset(const std::string& name,
                                  std::filesystem::path& path,
                                  bool allowSerializeAsText = false);
    int32_t GetInstanceIDFromPathAndFileID(const std::filesystem::path& path, int64_t localIdentifierInFile);

    // PR-SE3a-migrate -- look up the on-disk identity of an InstanceID.
    // Returns true only when the ID is mapped through Remapper (i.e.
    // it was generated by GetInstanceIDFromPathAndFileID at some
    // point). Used by:
    //   * WriterHook -- needs to translate an InstanceID being written
    //     into PPtr<T>::Transfer back into a (FileIdentifier, pathID)
    //     pair for the externals table.
    //   * Editor "save material" path -- so it can know which .zasset
    //     a referenced object came from without round-tripping through
    //     the Remapper directly.
    bool TryGetIdentityForInstance(int32_t instanceID,
                                   std::filesystem::path& outPath,
                                   int64_t& outLocalIdentifierInFile) const;

    // PR-SE3a-migrate -- override hook in EditorAssetManager only.
    // Given a .zasset path, returns the asset's GUID and runtime type
    // name from AssetRegistry (the source of truth); empty strings are
    // legitimate for newly-imported assets whose first scan hasn't
    // completed. Runtime base falls through to (empty, empty) -- the
    // standalone runtime build doesn't carry an AssetRegistry, and
    // PPtr cross-asset writes aren't generated by the runtime path
    // anyway (writes only happen in the editor).
    virtual void GetAssetGuidAndType(const std::filesystem::path& asset_path,
                                     std::string& outGuid,
                                     std::string& outAssetType) const;

    // PR-SE3a-migrate -- inverse of GetAssetGuidAndType. Editor uses
    // AssetRegistry's guid_to_path index. Runtime fallback returns
    // false (same rationale as above).
    virtual bool TryGetPathForGuid(const std::string& guid,
                                   std::filesystem::path& outPath) const;
    /**
     * @brief Load asset from file (auto-detect format by extension)
     * Supports .json (JSON) and .zasset (Binary) formats
     */
    template<typename AssetType>
    bool loadEditorResource(const std::string& asset_url, AssetType& out_asset) const
    {
        std::filesystem::path asset_path = GetEditorResourcePath(asset_url);
        std::string extension = asset_path.extension().string();

        return GET_SYSTEM(FileSystem)->loadAssetJson(asset_path, out_asset);
    }

    /**
     * @brief Save asset to file (auto-detect format by extension)
     * Supports .json (JSON) and .bin/.binary (Binary) formats
     */
    template<typename AssetType>
    bool saveAsset(AssetType& asset, const eastl::string& asset_url)
    {
        std::filesystem::path asset_path = GetFullPath(asset_url);
        std::string extension = asset_path.extension().string();
        std::string asset_type_ext = asset_path.stem().extension().string();
        std::transform(extension.begin(), extension.end(), extension.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        std::transform(asset_type_ext.begin(), asset_type_ext.end(), asset_type_ext.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

        if (extension == ".json")
        {
            const std::filesystem::path parent_path = asset_path.parent_path();

            if (!parent_path.empty())
            {
                std::filesystem::create_directories(parent_path);
            }
            return GET_SYSTEM(FileSystem)->saveAssetJson(asset, asset_path);
        }

        return WriteObjectToDiskThreadSafe(asset_path, asset);
    }

    std::filesystem::path GetFullPath(const eastl::string& relative_path) const;
    std::filesystem::path GetEditorResourcePath(const std::string& relative_path) const;
    std::string GetAssetTypeName(const std::filesystem::path& asset_path) const;

    // Editor-only: enumerate every .zasset whose runtime asset type matches
    // `asset_type` (e.g. "ShaderRes", "PrefabRes"). The base implementation
    // returns an empty vector -- only EditorAssetManager has the
    // AssetRegistry needed to answer this without a full directory walk.
    // Runtime callers typically don't need this (they look up by direct
    // path / GUID), so the empty default keeps standalone runtime builds
    // free of any directory-scan cost. When the override is present but
    // the registry is still warming up the override falls back to a
    // directory walk -- see EditorAssetManager.cpp / AssetRegistry's
    // CollectZAssetsOfType usage. Mirrors UE's
    // IAssetRegistry::GetAssetsByClass() exposed at the engine surface.
    virtual std::vector<std::filesystem::path>
    GetAssetsByType(const std::string& asset_type, const std::filesystem::path& search_root) const;

    SerializedFile* GetSerializedFile(const std::filesystem::path& path, LockFlags lockedFlags = kLockFlagNone);
    SerializedFile* GetSerializedFile(int serializedFileIndex, LockFlags localedFlags = kLockFlagNone);

    void AddStream();
    Object* ReadObject(std::filesystem::path& path, const Type* type);

    void UnloadStream(const std::filesystem::path& path);

    template<typename T>
    T* ReadObject(std::filesystem::path& path)
    {
        return static_cast<T*>(ReadObject(path, TypeOf<T>()));
    }
    int WriteFile(const std::filesystem::path& path, int serializedFileIndex, WriteData* writeData, int size);

    int GetSerializedFileIndexFromPath(const std::filesystem::path& path);
    bool WriteObjectToDiskThreadSafe(const std::filesystem::path& path, Object& object);
    bool WriteObjectsToDiskThreadSafe(const std::filesystem::path& path, Object** objects, const int64_t* identifiers, size_t count, TransferInstructionFlags transferFlags = kNoTransferInstructionFlags);

    // Text (YAML) multi-object graph I/O for scenes / prefabs. Same object-graph
    // model as the binary WriteObjectsToDiskThreadSafe (each object gets a local
    // fileID; PPtr / ImmediatePtr cross-references resolve through the shared
    // resolver), but encoded as human-readable, diff-friendly YAML. External
    // references to imported .zasset assets resolve through the same Remapper /
    // AssetRegistry hooks the binary path uses. See YamlObjectGraph.{h,cpp}.
    bool WriteObjectsToYaml(const std::filesystem::path& path, Object** objects, const int64_t* identifiers, size_t count);
    bool ReadObjectsFromYaml(const std::filesystem::path& path, std::vector<std::pair<int64_t, Object*>>& out);

protected:
    virtual int InsertPathNameInternal(const std::filesystem::path& path, bool create) = 0;
    virtual const std::string& PathIDToPathNameInternal(int pathID) const = 0;

private:
    StreamNameSpace& GetStreamNameSpaceInternal(int nameSpaceID);

    void CleanupStream(uint32_t serializedFileIndex);

    Remapper m_Remapper;
    using StreamContainer = std::vector<StreamNameSpace>;
    using IDRemap = std::unordered_map<int32_t, int32_t>;

    StreamContainer m_Streams;
    std::unordered_set<int> m_ActiveStreams;
    std::vector<IDRemap> m_GlobalToLocalNameSpace;
    std::vector<IDRemap> m_LocalToGlobalNameSpace;
};
