#ifndef MEGALIGHTS_DEFINITIONS_HLSLI
#define MEGALIGHTS_DEFINITIONS_HLSLI

#define ZENGINE_MEGALIGHTS_TILE_SIZE 8
#define ZENGINE_MEGALIGHTS_MAX_LIGHTS 1024
#define ZENGINE_MEGALIGHTS_MAX_LIGHTS_PER_TILE 64

// std430 / byte-address layout (128-byte header + 32-byte MegaLightGpu records).
#define ML_HEADER_BYTES 128
#define ML_LIGHT_STRIDE_BYTES 32

#endif
